### ISSUE TITLE
Import fix for segfault when searching for keys

### ISSUE THREAD

**Issue by kyrias** [karelzak/mutt-kz#101]
A bug introduced in mutt upstream broke searching for PGP keys (when trying to send encrypted emails), but was fixed again in February.

So could you import [the fix](http://dev.mutt.org/hg/mutt/rev/385d7434c9d6)?

**Comment by boyska** [comment]
I wrongly reported this bug upstream
http://dev.mutt.org/trac/ticket/3762
but it was already fixed there.

**Comment by karelzak** [comment]
On Fri, Jul 17, 2015 at 01:47:47AM -0700, BoySka wrote:
> I wrongly reported this bug upstream
> http://dev.mutt.org/trac/ticket/3762
> but it was already fixed there.

Backported to mutt-kz too. Thanks for your report!

    Karel

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com
