### ISSUE TITLE
Will all "standard/core" mutt features work in mutt-kz? ie, is mutt-kz a superset of mutt?

### ISSUE THREAD

**Issue by johnnyutahh** [karelzak/mutt-kz#102]
I'm new to mutt, mutt-kz, and Notmuch. Are all the standard/core features of mutt -- namely support for regular/non-Notmuch maildir folders -- work in mutt-kz?

Put another way: is mutt-kz a superset of mutt?

More details on my MUA investigation:
https://github.com/johnnyutahh/search-based-email#MUA_choice

**Comment by a-sk** [comment]
I used mutt-kz for a while, all features seem to work.
Regular/non-Notmuch maildir folders also work in mutt-kz.

**Comment by johnnyutahh** [comment]
Thanks @a-sk, that's helpful.
