### ISSUE TITLE
listing all unread tags

### ISSUE THREAD

**Issue by anarcat** [karelzak/mutt-kz#104]
one key feature of notmuch-emacs is the welcome screen, which seems to be missing from mutt-kz. i use it a lot to deal with massive amounts of mails... it looks like this right now here:

![v3iebbf](https://cloud.githubusercontent.com/assets/796623/14258375/3dca249a-fa70-11e5-9b6f-698d7b70ab9d.png)

i know i can set the equivalent of "saved searches" through the virtual-mailboxes command. however, i'd like to see the equivalent of the rest of the notmuch-hello page, which list all tags that have unread messages with the number of messages next to the tag.

i would have expected the y key to lead to that, for example.

any tips on how to do this?

**Comment by anarcat** [comment]
PS: i tried to send this as a question to the mailing list but it was under moderation for two days without response...

**Comment by suvayu** [comment]
What you are asking for is a new "screen or menu".  That is a lot of work and someone has to do it.  I have wanted to work on something like this for over a year now, but couldn't find the time.  As for the mailing list, are you subscribed?  All mailing lists hosted by fedoraproject requires you to be subscribed (to prevent spam).

**Comment by anarcat** [comment]
i was wondering if the `change-folder` command could be patched for that, or if some auto-completion scheme could be abused here... for example, maybe the `vfolder-from-query` command could behave similarly to `change-folder` and allow using `?` in macros to autocomplete. for example, i have this shortcut here that was very useful before i started using notmuch:

```
y                            M <change-folder>?<toggle-mailboxes>     show incoming mailboxes list
```

it would show me all folders i needed to look at...

as for the mailing list, i haven't subscribed as i wanted just to post this single mail, not join the development team. ;) is it okay if this is open as a feature request here?

**Comment by anarcat** [comment]
i found something similar posted on the mailing list here:

https://lists.fedoraproject.org/pipermail/mutt-kz/2013-May/000167.html

could it be the start of something that would do something here? :)

**Comment by anarcat** [comment]
moved to https://github.com/neomutt/neomutt/issues/628
