### ISSUE TITLE
modify-labels for entire thread

### ISSUE THREAD

**Issue by sjhorst** [karelzak/mutt-kz#106]
Is there a way to modify-labels for an entire thread? For example, I'd like to archive an entire thread with a single keystroke in mutt, but the modify-labels command only seems to work on a single message at a time. As far as I can tell, the type=threads item only works on queries, not tagging.

**Comment by karelzak** [comment]
On Thu, Sep 03, 2015 at 09:16:09AM -0700, Stephen Horst wrote:
> Is there a way to modify-labels for an entire thread? For example,
> I'd like to archive an entire thread with a single keystroke in
> mutt, but the modify-labels command only seems to work on a single
> message at a time. As far as I can tell, the type=threads item only
> works on queries, not tagging.

<modify-labels> works with standard mutt <tag-prefix>, all you need is
to mark necessary messages by tag -- press 't' or use <tag-thread>,
for example I have 

    bind index <insert> tag-thread

to mark all messages in the thread by "insert" key. Then you can apply
arbitrary command (e.g. modify-labels) after ";" (aka <tag-prefix>).

    Karel

-- 
 Karel Zak  <kzak@redhat.com>
 http://karelzak.blogspot.com
