### ISSUE TITLE
Reflect open folder in sidebar

### ISSUE THREAD

**Issue by madduck** [karelzak/mutt-kz#110]
Hope this is the right place to report this…

When I open mutt-kz on a folder, say `=debian`, it'd be nice if that folder was also selected in the sidebar. Currently, the selection is always on the first folder, which I find confusing.

Thanks,
martin

**Comment by madduck** [comment]
I note that `change-folder` updates the sidebar correctly, so all that's missing is a sync on startup, e.g. when I run

    mutt-kz -f =debian

to open up the `=debian` mailbox straight away.

**Comment by flatcap** [comment]
@madduck 
There's a new version of mutt-kz (1.6.0.1) which includes the new Sidebar.
This should fix your problem.

**Note:** the sidebar now has two "cursors".
The Indicator shows the current, open, folder and should reflect what you see in the index.
The Highlight is a movable cursor for selection only.
They can be coloured with "sidebar_indicator" and "sidebar_highlight" respectively.
