### ISSUE TITLE
Adding bounced email to notmuch DB?

### ISSUE THREAD

**Issue by frankqux** [karelzak/mutt-kz#120]
This may be a misunderstanding on my part of what exactly bouncing an email is supposed to be, but is there a way to add it to notmuch, the same way sent, replied, and forwarded emails are? Currently, when I bounce an email I see that it's sent (either by asking someone to confirm or sending it to myself) but see no record of the email (neither in notmuch DB nor in my maildir).

**Comment by duckdalbe** [comment]
Notmuch indexes by Message-ID. Bounced messages don't get a new Message-ID so to notmuch it's the same message as the incoming one (which in a way is actually true).

**Comment by anarcat** [comment]
yep - this should be closed, IMHO.

**Comment by frankqux** [comment]
Cool, thanks for clarifying.
