### ISSUE TITLE
is long query in virtual-mailboxes working?

### ISSUE THREAD

**Issue by jhutar** [karelzak/mutt-kz#122]
I'm using this:

    mutt-kz-1.5.23.1-2.20150717.git.24c06e70.fc23.x86_64
    notmuch-0.21-1.fc23.x86_64

and in .muttrc I have:

    virtual-mailboxes \
       [...] \
       'UNSORTED'   'notmuch://?query=NOT ( tag:inbox or tag:archive or tag:mailinglist1 or tag:mailinglist2 or [...] )'

The string with query is 511 chars long if there is some limit. I just want folder which would catch all emails not sorted in all other virtual folders.

With this I still see emails tagged with, say, "mailinglist19" in the UNSORTED virtual folder. There is no error printed by mutt.

**Comment by yeled** [comment]
there is a patch by @blami about `_POSIX_PATH_MAX` on the mailing list and then a redaction. I also have this issue with large queries.

**Comment by jhutar** [comment]
Oh, I'm glad that it is not just me :-)

**Comment by timofonic** [comment]
Any updates?

**Comment by karelzak** [comment]
The Should be fixed.
