### ISSUE TITLE
Why am  I seeing "No virtual folder, aborting"

### ISSUE THREAD

**Issue by amandabee** [karelzak/mutt-kz#126]
I was just starting to use tagging in mutt-kz and used to be able to use the tick (<kbd>`</kbd>) to trigger the tag prompt until this week when  I started seeing an error instead: "No virtual folder, aborting." -- I can't figure out what I might have done to bring this on or how to troubleshoot it. 

I tried [asking on Stack Exchange](http://unix.stackexchange.com/questions/273743/why-am-i-getting-no-virtual-folder-aborting-when-i-try-to-tag-messages-in-mut) but so far no one has bitten. 

The error is defined at <https://github.com/karelzak/mutt-kz/blob/master/curs_main.c> but I can't quite decipher how I'd be triggering it with <kbd>`</kbd>.

My sanitized config lives at <https://gist.github.com/amandabee/cf7faad0a6f2afc485ee>

I'm at a loss and would love any pointers you can offer me.

**Comment by suvayu** [comment]
Are you in a virtual folder when you attempt to tag?  Tagging works only in a virtual folder, so it will fail in `=INBOX` but will succeed in `tag:inbox`.

**Comment by amandabee** [comment]
Bingo. I have a hundred more questions, but at least for now I know how to make tagging work and the next person who searches for the error will find some kind of troubleshooting trail.

**Comment by suvayu** [comment]
I think for questions you should use the [mailing list](https://admin.fedoraproject.org/mailman/listinfo/mutt-kz).

**Comment by amandabee** [comment]
Unfortunately, even though I definitely subscribed to the list, when I tried to post I got a notice that my post was being held in a queue. So ... so far I don't think I'm able to participate on the mailing list. :(

I'll live.
