### ISSUE TITLE
sidebar_delim isn't recognized in 1.6.0.1

### ISSUE THREAD

**Issue by sadsfae** [karelzak/mutt-kz#128]
Hi there,

The setting "sidebar_delim=" option isn't recognized once updating from mutt-kz 1.5.23.1-2.20160103.git.f13afeb3.fc22 --> mutt-kz-1.6.0.1-1

-- snip --
Error in .muttrc, line 216: sidebar_delim: unknown variable
source:
--snip--

**Comment by flatcap** [comment]
The new version of Notmuch (1.6.0.1) includes the new version of Sidebar.
Some of the sidebar config options were renamed to make the meaning clearer and to better match Mutt's config.

Here's a list of the changes:
http://www.neomutt.org/sidebar-intro.html#intro-sidebar-config-changes

**Comment by sadsfae** [comment]
@flatcap thanks for that, I'm sorted now.
