### ISSUE TITLE
Configuring mutt-kz without enabling sidebar results in compile error

### ISSUE THREAD

**Issue by romanofski** [karelzak/mutt-kz#135]
If I configure mutt-kz according to README.notmuch just by using `--enable-notmuch` I run into the following compile error:

```
browser.c: In function ‘examine_vfolders’:
browser.c:529:42: error: ‘BUFFY {aka struct buffy_t}’ has no member named ‘msg_count’
       nm_nonctx_get_count(tmp->path, &tmp->msg_count, &tmp->msg_unread);
                                          ^
browser.c:529:59: error: ‘BUFFY {aka struct buffy_t}’ has no member named ‘msg_unread’
       nm_nonctx_get_count(tmp->path, &tmp->msg_count, &tmp->msg_unread);
                                                           ^
browser.c:531:12: error: ‘BUFFY {aka struct buffy_t}’ has no member named ‘msg_unread’
         tmp->msg_unread, tmp->msg_count);
            ^
browser.c:531:29: error: ‘BUFFY {aka struct buffy_t}’ has no member named ‘msg_count’
         tmp->msg_unread, tmp->msg_count);
```
Checking what is defined in buffy.h it seems that it is mandatory to configure with `--enable-sidebar` as well.

So either it needs to be mentioned in the README, or there is a leaky abstraction since I don't think everyone needs the sidebar when using notmuch?

**Comment by flatcap** [comment]
@romanofski 
Thanks for the report.  I've already submitted a pull-request as a workaround #129 
(for now, --enable-notmuch forcibly enables --enable-sidebar)

Ideally, notmuch and sidebar should be separable, but there's currently a small overlap.

**Comment by romanofski** [comment]
W00hoo @flatcap - many thanks!

**Comment by karelzak** [comment]
Fixed, git pull and make to fix.
