### ISSUE TITLE
set sidebar_folder_indent causes segV

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [karelzak/mutt-kz#137]
I have a number of mboxes and if I set:
   set sidebar_folder_indent
(I've tried with and without "=yes")
I'm using this in conjunction with:
  set sidebar_short_path
 
then starting mutt just displays:

Sorting mailbox...Segmentation fault (core dumped)

**Comment by flatcap** [comment]
@kambiz-aghaiepour 
Which version of mutt are you using? 
```
mutt -v | head -n1
```

Can you give me a list of your mailbox names.
Also, can you show me all your sidebar variables:
```
mutt -D | grep sidebar
```

**Comment by flatcap** [comment]
I've committed a fix to the [neomutt/sidebar](https://github.com/neomutt/neomutt/tree/feature/sidebar) branch.

In the mean time, you can work around the problem by stripping any trailing /'s from the end of mailboxes commands:

    set folder="~/mail/folder"
    mailboxes "~/mail/folder/"

**Comment by flatcap** [comment]
The latest version of the Sidebar in NeoMutt 20160416 fixes this bug.
Pull-request #138 will fix the bug in Mutt-KZ.

**Comment by karelzak** [comment]
Fixed, git pull and make to fix.
