### ISSUE TITLE
tag completion with dashes

### ISSUE THREAD

**Issue by xunam** [karelzak/mutt-kz#149]
Hi,

I have a lot of tags with dashes in them, in the format `foo-bar`, I use these to structure the set of tags. When using completion in `<modify-labels>`, things get mixed up because, apparently, dashes inside tags are mistaken for an initial dash used to remove tags.

For instance, assume I have tags `foo-bar` and `foo-baz` (and no other tag starting with `foo`). If call `<modify-labels>` and start typing `+foo` then the first tab yields `+foo-` (as expected), then pressing tab repeatedly yields `+foo-foo-bar` then `+foo-foo-foo-baz` then `+foo-foo-foo-foo` and the cycle restarts, adding a new `foo` each time.

This looks like something easy to fix, but I didn't try diving into the code yet...

**Comment by flatcap** [comment]
Hi @xunam, thanks for the bug report.

The Mutt-KZ project is now deprecated in favour of [NeoMutt](https://www.neomutt.org/)
(It contains all the features of Mutt-KZ, and more).

I have fixed this bug in the latest version of [NeoMutt (2016-09-16)](https://github.com/neomutt/neomutt/releases/tag/neomutt-20160916).

> This looks like something easy to fix

Yes, it was :-)

**Comment by xunam** [comment]
Nice! I checked out the last version and it works fine.

Actually I was already using NeoMutt, the [feature page](https://www.neomutt.org/feature/notmuch/) on NeoMutt's web site points to here for the home page and source, so I assumed it was the right place for bug reports about the notmuch feature.
