### ISSUE TITLE
rename: No such file or directory (errno = 2)

### ISSUE THREAD

**Issue by larsks** [karelzak/mutt-kz#16]
I'm regularlly getting this error from mutt-kz:

    rename: No such file or directory (errno = 2)

I was able to trigger it just now by:

- Opening a mailbox
- Selected a (N)ew message and deleting it (so the status was now ND)
- Select '$' to synchronize the mailbox.

At this point mutt prints the `rename` error, and becomes unusable -- any attempt to change to another folder will report the error and fail.  Exiting mutt is only possible via the `exit` command.

I'm having trouble pinning down the exact sequence of events that leads to this error, but I suspect it has to do with mutt renaming files when the status changes and notmuch not being aware of the change.

**Comment by hari-rangarajan** [comment]
I have this problem too. I think it has to do with the maildir folder contents modified async (I have mbsync running as cron job). Has anyone figured a fix for this yet?

Thanks!

**Comment by anarcat** [comment]
i also have this problem. there were discussions on the mailing list about this as well:

https://lists.fedoraproject.org/pipermail/mutt-kz/2013-November/000248.html
https://lists.fedoraproject.org/pipermail/mutt-kz/2013-May/000168.html

**Comment by shioyama** [comment]
Seeing the same issue.
