### ISSUE TITLE
Sides of Sidebar are White

### ISSUE THREAD

**Issue by noctuid** [karelzak/mutt-kz#82]
This is what the sidebar looks like for me with mutt-kz:
![Alt text](http://i.imgur.com/Id8us6H.png)

It looks pretty ugly to me.

This is what it looks like with the lunar-linux sidebar patch:
![Alt text](http://i.imgur.com/oyg8pI5.png)

**Comment by jhutar** [comment]
With mutt-kz-1.6.0.1-1.fc23.x86_64 it is `color sidebar_divider black white` now. See http://www.neomutt.org/feature/sidebar/#sidebar-colors
